features:
  otel: true
  grpcServer: true
  httpServer: true
  
grpcServer:
  host: 0.0.0.0
  port: 50051
  trace: all
  logs:
    verbosity: info
  tls:
    disable: true
    checkClientCert: true

httpServer:
  port: 8080

otel:
  service:
    name: ms
    namespace: ms
  trace:
    host: localhost
    port: 4317
    logToConsole: true
  metrics:
    port: 9464
  logs:
    level: debug
    format: json
    time:
      format: 'YYYY-MM-DD HH:mm:ss'
    summary:
      logToConsoleLevels:
        - debug
        - info
  
postgresStorage:
  connection:
    host: localhost
    port: 5432
  pool:
    enabled: true
    min: 1
    max: 5
  # credentials:
  #   inflation:
  #     username: postgres-config
  #     password: postgres-config
  queries:
    timeout: 5000
  mockConnection:
    enabled: false
    minDelay: 500
    maxDelay: 1000

  
