version: "3.9"
services:
  ms:
    volumes:
      - vscode-extensions:/root/.vscode-server/extensions
      - vscode-extensions-insiders:/root/.vscode-server-insiders/extensions
      - ~/.config/gh:/home/node/.config/gh:ro
      - ~/.config/helm:/home/node/.config/helm
    command: /bin/sh -c "while sleep 1000; do :; done"
    networks:
      - nextjs_grpc

volumes:
  vscode-extensions:
  vscode-extensions-insiders:

networks:
  nextjs_grpc:
    external: true
