features:
  otel: true
  grpcServer: true
  httpServer: true
  
grpcServer:
  host: 0.0.0.0
  port: 50051
  trace: all
  logs:
    verbosity: info
  tls:
    enabled: false
    checkClientCert: false

httpServer:
  port: 8080

otel:
  service:
    name: nextjs-grpc-ms
    namespace: ms
  trace:
    host: localhost
    port: 4317
    logToConsole: true
  metrics:
    port: 9464
  logs:
    level: debug
    format: json
    time:
      format: 'YYYY-MM-DD HH:mm:ss'
    summary:
      redactedPhrase: REDACTED
      logToConsoleLevels:
        - debug
        - info

postgresStorage:
  connection:
    host: localhost
    port: 5432
  pool:
    enabled: true
    min: 1
    max: 5
  queries:
    timeout: 5000
  mockConnection:
    enabled: false
    minDelay: 3000
    maxDelay: 1000

  
