FROM node:19-slim AS builder

ARG ROOT_PASS
ARG USERNAME
ARG GROUP

RUN sh -c 'echo "root:$ROOT_PASS" | chpasswd'
RUN sh -c 'echo "node:$ROOT_PASS" | chpasswd'

RUN apt update && apt install -y vim curl sudo
WORKDIR  /utkusarioglu-com/projects/nextjs-grpc/ms
COPY ms /utkusarioglu-com/projects/nextjs-grpc/ms
COPY proto /utkusarioglu-com/projects/nextjs-grpc/proto
RUN chown -R $CONTAINER_USERNAME:$CONTAINER_GROUP /utkusarioglu-com
RUN yarn
RUN yarn build

FROM node:19-slim AS runner

ARG ROOT_PASS
ARG USERNAME
ARG GROUP

RUN sh -c 'echo "root:$ROOT_PASS" | chpasswd'
RUN sh -c 'echo "node:$ROOT_PASS" | chpasswd'

WORKDIR  /utkusarioglu-com/projects/nextjs-grpc/ms
COPY --from=builder /utkusarioglu-com/projects/nextjs-grpc/ms/dist dist
COPY --from=builder /utkusarioglu-com/projects/nextjs-grpc/ms/scripts scripts
COPY --from=builder /utkusarioglu-com/projects/nextjs-grpc/ms/package.json package.json
COPY --from=builder /utkusarioglu-com/projects/nextjs-grpc/ms/yarn.lock yarn.lock

WORKDIR  /utkusarioglu-com/projects/nextjs-grpc
COPY --from=builder /utkusarioglu-com/projects/nextjs-grpc/proto proto

WORKDIR  /utkusarioglu-com/projects/nextjs-grpc/ms
RUN yarn --frozen-lockfile --prod

USER $USERNAME
ENTRYPOINT scripts/start.sh
