FROM node:19-slim AS builder

ARG ROOT_PASS=ROOT
ARG USERNAME=1000
ARG GROUP=1000

RUN sh -c 'echo "root:$ROOT_PASS" | chpasswd'
RUN sh -c 'echo "node:$ROOT_PASS" | chpasswd'
RUN apt update && apt install -y vim curl sudo
WORKDIR  /utkusarioglu-com/projects/nextjs-grpc/ms
COPY ms /utkusarioglu-com/projects/nextjs-grpc/ms
COPY proto /utkusarioglu-com/projects/nextjs-grpc/proto
RUN chown -R $CONTAINER_USERNAME:$CONTAINER_GROUP /utkusarioglu-com
RUN yarn
RUN yarn build

FROM node:19-slim AS runner
WORKDIR  /utkusarioglu-com/projects/nextjs-grpc/ms
COPY --from=builder /utkusarioglu/projects/nextjs-grpc/ms/dist dist
COPY --from=builder /utkusarioglu/projects/nextjs-grpc/ms/scripts scripts
COPY --from=builder /utkusarioglu/projects/nextjs-grpc/ms/package.json package.json
COPY --from=builder /utkusarioglu/projects/nextjs-grpc/ms/yarn.lock yarn.lock
RUN yarn --frozen-lockfile --prod
USER node
ENTRYPOINT scripts/start.sh
