FROM node:19-slim AS builder

ARG ROOT_PASS
ARG USERNAME
ARG GROUP
ARG PROTO_REPO_RELPATH
ARG PROJECT_ABSPATH=/utkusarioglu-com/projects/nextjs-grpc
ARG PROTO_REPO_ABSPATH="$PROJECT_ABSPATH/$PROTO_REPO_RELPATH"
ARG REPO_ABSPATH="$PROJECT_ABSPATH/ms"

RUN sh -c 'echo "root:$ROOT_PASS" | chpasswd'
RUN sh -c 'echo "node:$ROOT_PASS" | chpasswd'

RUN apt update && apt install -y jq

WORKDIR $REPO_ABSPATH
COPY ms $REPO_ABSPATH
RUN chown -R $CONTAINER_USERNAME:$CONTAINER_GROUP $PROJECT_ABSPATH
RUN ls -al $REPO_ABSPATH

COPY proto $PROTO_REPO_ABSPATH
WORKDIR $PROTO_REPO_ABSPATH
RUN yarn --immutable
RUN yarn generate:ms
RUN ls -al $PROJECT_ABSPATH/proto

WORKDIR $REPO_ABSPATH
RUN yarn
RUN yarn build

FROM node:19-slim AS runner

ARG ROOT_PASS
ARG USERNAME
ARG GROUP
ARG PROJECT_ABSPATH=/utkusarioglu-com/projects/nextjs-grpc

RUN sh -c 'echo "root:$ROOT_PASS" | chpasswd'
RUN sh -c 'echo "node:$ROOT_PASS" | chpasswd'

WORKDIR $PROJECT_ABSPATH/ms
COPY --from=builder $PROJECT_ABSPATH/ms/dist dist
COPY --from=builder $PROJECT_ABSPATH/ms/scripts scripts
COPY --from=builder $PROJECT_ABSPATH/ms/config config
COPY --from=builder $PROJECT_ABSPATH/ms/package.json package.json
COPY --from=builder $PROJECT_ABSPATH/ms/yarn.lock yarn.lock
COPY --from=builder $PROJECT_ABSPATH/ms/tsconfig-paths.js tsconfig-paths.js
COPY --from=builder $PROJECT_ABSPATH/ms/tsconfig.json tsconfig.json

RUN rm -rf $PROJECT_ABSPATH/ms/config/user

# WORKDIR $PROJECT_ABSPATH/proto
# COPY --from=builder $PROJECT_ABSPATH/proto/src src
# RUN rm -rf src/defunct

WORKDIR $PROJECT_ABSPATH/ms
RUN yarn --frozen-lockfile --prod

USER $USERNAME
ENTRYPOINT scripts/start.sh
