name: build-and-push

on:
  push:
    tags:
      - "**.**.**"
      - "experiment/**/**/**"
    paths:
      - src/**
      - .github/workflows/build-test-push.wfc.yml
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test-push:
    uses: ./.github/workflows/build-test-push.wfc.yml
    secrets: inherit
